[package]
name = "omni_desktop_host"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "40.0"
wasmtime-wasi = "40.0"
capnp = "0.21"
thiserror = "1.0"
itertools = "0.14.0"
paste = "1.0"
lazy_static = "1.5.0"
wit-parser = "0.244.0"
anyhow = "1.0.100" #required because of wit-parser
pipe-trait = "0.4.0"
regex = "1.12.2"

[build-dependencies]
capnpc = "0.21"
